apiVersion: v1
kind: Service
metadata:
 name: grafana-mon
 namespace: kube-system
 labels:
  name: grafana-mon
spec:
 selector:
  k8s-app: grafana
 type: NodePort
 ports:
  - name: grafana
    port: 3000
    targetPort: 3000
    nodePort: 3010
